name: Create and Publish Docker Image to DockerHub

on:
  workflow_call:
    inputs:
      dockerImage:
        description: Docker Image
        required: true
        type: string
      dockerImageTag:
        description: Docker Image tag (comma separated for multiple)
        default: "latest"
        required: false
        type: string
      dockerFileContext:
        description: Dockerfile Context
        default: "."
        required: false
        type: string
      signImage:
        description: Enable Docker Image Signing (DCT)
        type: boolean
        required: false
        default: false
    secrets:
      DOCKER_USERNAME:
        description: Docker Hub username
        required: true
      DOCKER_PASSWORD:
        description: Docker Hub user password
        required: true
      DOCKER_PRIVATE_KEY_ID:
        description: Docker Hub Signing Private Key ID
        required: false
      DOCKER_PRIVATE_KEY:
        description: Docker Hub Signing Private Key
        required: false
      DOCKER_PRIVATE_KEY_PASSPHRASE:
        description: Docker Hub Signing Private Key Passphrase
        required: false

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.additional-jsontags.outputs.tags }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build list of additional tags
        id: additional-tags
        uses: actions/github-script@v7
        with:
          script: |
            core.setOutput('tags', `${{ inputs.dockerImageTag }}`.split(",").join("\n"))     
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.dockerImage }}
          tags: |
            ${{ steps.additional-tags.outputs.tags }}
      - name: Build and push Docker image to Dockerhub
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.dockerFileContext }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build Json array of tags for Docker Signing
        id: additional-jsontags
        run: |
          echo tags=$(echo ${{ inputs.dockerImageTag }} | sed 's/,/\n/g'| jq --raw-input | jq --slurp -c) >> $GITHUB_OUTPUT
  sign-image:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    if: ${{ inputs.signImage == true }}
    strategy:
      matrix:
        tags: ${{ fromJson(needs.build-and-push-image.outputs.tags) }}
      fail-fast: false
      max-parallel: 1
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull image ${{ inputs.dockerImage }}:${{ matrix.tags }}
        run: docker pull ${{ inputs.dockerImage }}:${{ matrix.tags }}    
      - name: Sign the published Dockerhub Docker image with DCT
        uses: sudo-bot/action-docker-sign@latest
        with:
          image-ref: ${{ inputs.dockerImage }}:${{ matrix.tags }}
          private-key-id: "${{ secrets.DOCKER_PRIVATE_KEY_ID }}"
          private-key: ${{ secrets.DOCKER_PRIVATE_KEY }}
          private-key-passphrase: ${{ secrets.DOCKER_PRIVATE_KEY_PASSPHRASE }}
