name: Create and Publish Docker Image to DockerHub

on:
  workflow_call:
    inputs:
      dockerImage:
        description: Docker Image
        required: true
        type: string
      dockerImageTag:
        description: Docker Image tag
        default: "latest"
        required: false
        type: string
      dockerFileContext:
        description: Dockerfile Context
        default: "."
        required: false
        type: string
      signImage:
        description: Enable Docker Image Signing (DCT)
        type: boolean
        required: false
        default: false
    secrets:
      DOCKER_USERNAME:
        description: Docker Hub username
        required: true
      DOCKER_PASSWORD:
        description: Docker Hub user password
        required: true
      DOCKER_PRIVATE_KEY_ID:
        description: Docker Hub Signing Private Key ID
        required: false
      DOCKER_PRIVATE_KEY:
        description: Docker Hub Signing Private Key
        required: false
      DOCKER_PRIVATE_KEY_PASSPHRASE:
        description: Docker Hub Signing Private Key Passphrase
        required: false

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ inputs.dockerImage }}
          tags: |
            type=raw,value=${{ inputs.dockerImageTag }}
      - name: Build and push Docker image to Dockerhub
        uses: docker/build-push-action@v4
        with:
          context: ${{ inputs.dockerFileContext }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Sign the published Dockerhub Docker image with DCT
        uses: sudo-bot/action-docker-sign@latest
        if: ${{ inputs.signImage == 'true' }}
        with:
          image-ref: ${{ steps.meta.outputs.tags }}
          private-key-id: "${{ secrets.DOCKER_PRIVATE_KEY_ID }}"
          private-key: ${{ secrets.DOCKER_PRIVATE_KEY }}
          private-key-passphrase: ${{ secrets.DOCKER_PRIVATE_KEY_PASSPHRASE }}
