name: CI Build
on:
  workflow_call:
    inputs:
      maven_version:
        description: Maven version
        default: "3.9.9"
        required: false
        type: string
      maven_profiles:
        description: Maven Profiles
        default: "exo-release"
        required: false
        type: string
      extra_maven_opts:
        description: Extra Maven OPTS
        default: ""
        required: false
        type: string
      jdk_major_version:
        description: JDK Major version (eg 8, 11, 14, 17, 21,...)
        default: 17
        required: false
        type: number
      jdk_distribution:
        description: OpenJDK Adopted Distribution (temurin, zulu, adopt, liberica,...)
        default: "zulu"
        required: false
        type: string
      maximize_build_space:
        description: Maximize Build Space for Bigger Projects Unit tests based on files and blocks
        type: boolean
        required: false
        default: false
    secrets:
      NEXUS_USERNAME:
        required: true
      NEXUS_PASSWORD:
        required: true
      SWF_TOKEN:
        required: false
env:
  SETTINGS_XML_URL: 'http://storage.exoplatform.org/public/githubci/maven-settings.xml'
jobs:
  build-ci:
    name: CI Build
    runs-on: ubuntu-latest
    timeout-minutes: 120
    permissions:
      pull-requests: write
    steps:
      - name: PR BUILD
        uses: exo-actions/pr-action@v1
        with:
          maven_version: ${{ inputs.maven_version }}
          maven_profiles: ${{ inputs.maven_profiles }}
          extra_maven_opts: ${{ inputs.extra_maven_opts }}
          jdk_major_version: ${{ inputs.jdk_major_version }}
          jdk_distribution: ${{ inputs.jdk_distribution }}
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          M2_SETTINGS_FILE_URL: ${{ env.SETTINGS_XML_URL }}
          

            