name: Crowdin download Action for Meeds-io

on:
  workflow_call:
    inputs:
      CROWDIN_DEVELOP_VERSION:
        description: Module develop version
        default: "7.0.x"
        required: false
        type: string
      CROWDIN_MAINTENANCE_EXO_VERSION:
        description: Module stable version
        default: "6.5.x-exo"
        required: false
        type: string
      CROWDIN_MAINTENANCE_BRANCH_VERSION:
        description: Maintenance Crowdin branch
        default: "maintenance"
        required: false
        type: string
      CROWDIN_ALLOW_DEVELOP_EXO_DOWNLOAD:
        description: Allow or not merge for develop-exo branch
        default: "true"
        required: false
        type: string
      CROWDIN_ALLOW_DEVELOP_MEED_DOWNLOAD:
        description: Allow or not merge for develop-meed branch
        default: "true"
        required: false
        type: string
      CROWDIN_ALLOW_MAINTENANCE_DOWNLOAD:
        description: Allow or not merge for maintenance branch
        default: "true"
        required: false
        type: string
      CROWDIN_LANGUAGES_ARG:
        description: Crowdin args for used languages
        default: "-l ar -l aro -l az -l ca -l ceb -l co -l cs -l de -l el -l en -l es-ES -l eu -l fa -l fi -l fil -l fr -l hi -l hu -l id -l it -l ja -l ko -l lt -l ms -l nl -l no -l pcm -l pl -l pt-BR -l pt-PT -l ro -l ru -l sk -l sl -l sq -l sv-SE -l th -l tl -l tr -l uk -l ur-IN -l vi -l zh-CN -l zh-TW"
        required: false
        type: string
      YML_CROWDIN_LANGUAGES_ARG:
        description: Crowdin language env var for crowdin.yml file
        default: '"_en!": "","ar_SA": "ar","ar_OM": "aro","az_AZ": "az","ca_ES": "ca","ceb_PH": "ceb", "co_FR": "co","cs_CZ": "cs","de_DE": "de","el_GR": "el","en_US": "en","es_ES": "es_ES","eu_ES": "eu","fa_IR": "fa", "fi_FI": "fi","fil_PH": "fil","fr_FR": "fr","hi_IN": "hi","hu_HU": "hu","id_ID": "id","it_IT": "it","ja_JP": "ja", "kab_KAB": "kab","ko_KR": "ko","lt_LT": "lt","ms_MY": "ms","nl_NL": "nl","no_NO": "no","pcm_NG": "pcm","pl_PL": "pl", "pt_BR": "pt_BR","pt_PT": "pt_PT","ro_RO": "ro","ru_RU": "ru","sk_SK": "sk","sl_SI": "sl","sq_AL": "sq", "sv_SE": "sv_SE","th_TH": "th","tl_PH": "tl","tr_TR": "tr","uk_UA": "uk","ur_IN": "ur_IN","vi_VN": "vi", "zh_CN": "zh_CN","zh_TW": "zh_TW",'
        required: false
        type: string
    secrets:
      CROWDIN_GITHUB_TOKEN:
        required: true
      CROWDIN_PROJECT_ID:
        required: true
      CROWDIN_PERSONAL_TOKEN:
        required: true
      SWF_GPG_PRIVATE_KEY:
        required: true
      SWF_GPG_PASSPHRASE:
        required: true
jobs:
  # develop-exo workflow
  crowdin-download-develop-exo:
    if: inputs.CROWDIN_ALLOW_DEVELOP_EXO_DOWNLOAD == 'true'
    uses: exoplatform/swf-scripts/.github/workflows/download-crowdin-generic.yml@master
    with: 
      PROJECT_VERSION: ${{ inputs.CROWDIN_DEVELOP_VERSION }}-exo
      PROJECT_BRANCH: develop-exo
      CROWDIN_BRANCH: develop-exo
      CROWDIN_LANGUAGES_ARG: ${{ inputs.CROWDIN_LANGUAGES_ARG }}
      YML_CROWDIN_LANGUAGES_ARG: ${{ inputs.YML_CROWDIN_LANGUAGES_ARG }}
    secrets: inherit
  # develop-meed workflow
  crowdin-download-develop-meed:
    if: always() && inputs.CROWDIN_ALLOW_DEVELOP_MEED_DOWNLOAD == 'true'
    needs: [crowdin-download-develop-exo]
    uses: exoplatform/swf-scripts/.github/workflows/download-crowdin-generic.yml@master
    with: 
      PROJECT_VERSION: ${{ inputs.CROWDIN_DEVELOP_VERSION }}-meed
      PROJECT_BRANCH: develop-meed
      CROWDIN_BRANCH: develop-meed
      CROWDIN_LANGUAGES_ARG: ${{ inputs.CROWDIN_LANGUAGES_ARG }}
      YML_CROWDIN_LANGUAGES_ARG: ${{ inputs.YML_CROWDIN_LANGUAGES_ARG }}
    secrets: inherit
  # stable/x.x.x-exo workflow
  crowdin-download-stable-exo:
    if: always() && inputs.CROWDIN_ALLOW_MAINTENANCE_DOWNLOAD == 'true'
    needs: [crowdin-download-develop-meed]
    uses: exoplatform/swf-scripts/.github/workflows/download-crowdin-generic.yml@master
    with: 
      PROJECT_VERSION: ${{ inputs.CROWDIN_MAINTENANCE_EXO_VERSION }}
      PROJECT_BRANCH: stable/${{ inputs.CROWDIN_MAINTENANCE_EXO_VERSION }}
      CROWDIN_BRANCH: ${{ inputs.CROWDIN_MAINTENANCE_BRANCH_VERSION }}
      CROWDIN_LANGUAGES_ARG: ${{ inputs.CROWDIN_LANGUAGES_ARG }}
      YML_CROWDIN_LANGUAGES_ARG: ${{ inputs.YML_CROWDIN_LANGUAGES_ARG }}
    secrets: inherit
