name: Crowdin download Action for exoplatform

on:
  workflow_call:
    inputs:
      CROWDIN_DEVELOP_VERSION:
        description: Module develop version
        default: "7.0.x"
        required: false
        type: string
      CROWDIN_MAINTENANCE_EXO_VERSION:
        description: Module stable version
        default: "6.5.x"
        required: false
        type: string
      CROWDIN_ALLOW_DEVELOP_DOWNLOAD:
        description: Allow or not merge for develop branch
        default: "true"
        required: false
        type: string
      CROWDIN_ALLOW_MAINTENANCE_DOWNLOAD:
        description: Allow or not merge for maintenance branch
        default: "true"
        required: false
        type: string
    secrets:
      CROWDIN_GITHUB_TOKEN:
        required: true
      CROWDIN_PROJECT_ID:
        required: true
      CROWDIN_PERSONAL_TOKEN:
        required: true
      SWF_GPG_PRIVATE_KEY:
        required: true
      SWF_GPG_PASSPHRASE:
        required: true

jobs:

  # develop workflow
  crowdin-download-develop:
    if: inputs.CROWDIN_ALLOW_DEVELOP_DOWNLOAD == 'true'
    uses: exoplatform/swf-scripts/.github/workflows/download-crowdin-generic.yml@master
    with: 
      PROJECT_VERSION: ${{ inputs.CROWDIN_DEVELOP_VERSION }}
      PROJECT_BRANCH: develop
    secrets: inherit
  # stable/x.x.x
  crowdin-download-stable:
    if: always() && inputs.CROWDIN_ALLOW_MAINTENANCE_DOWNLOAD == 'true'
    needs: [crowdin-download-develop]
    uses: exoplatform/swf-scripts/.github/workflows/download-crowdin-generic.yml@master
    with: 
      PROJECT_VERSION: ${{ inputs.CROWDIN_MAINTENANCE_EXO_VERSION }}
      PROJECT_BRANCH: stable/${{ inputs.CROWDIN_MAINTENANCE_EXO_VERSION }}
    secrets: inherit