name: Crowdin download Action for Meeds-io

on:
  workflow_call:
    inputs:
      CROWDIN_DEVELOP_VERSION:
        description: Module develop version
        default: "7.0.x"
        required: false
        type: string
      CROWDIN_MAINTENANCE_EXO_VERSION:
        description: Module stable version
        default: "6.5.x-exo"
        required: false
        type: string
      CROWDIN_MAINTENANCE_BRANCH_VERSION:
        description: Maintenance Crowdin branch
        default: "6.5.x"
        required: false
        type: string
      CROWDIN_ALLOW_DEVELOP_EXO_DOWNLOAD:
        description: Allow or not merge for develop-exo branch
        default: "true"
        required: false
        type: string
      CROWDIN_ALLOW_DEVELOP_MEED_DOWNLOAD:
        description: Allow or not merge for develop-meed branch
        default: "true"
        required: false
        type: string
      CROWDIN_ALLOW_MAINTENANCE_DOWNLOAD:
        description: Allow or not merge for maintenance branch
        default: "true"
        required: false
        type: string
    secrets:
      CROWDIN_GITHUB_TOKEN:
        required: true
      CROWDIN_PROJECT_ID:
        required: true
      CROWDIN_PERSONAL_TOKEN:
        required: true
      SWF_GPG_PRIVATE_KEY:
        required: true
      SWF_GPG_PASSPHRASE:
        required: true
jobs:
  # develop-exo workflow
  crowdin-download-develop-exo:
    if: inputs.CROWDIN_ALLOW_DEVELOP_EXO_DOWNLOAD == 'true'
    uses: exoplatform/swf-scripts/.github/workflows/download-crowdin-generic.yml@master
    with: 
      PROJECT_VERSION: ${{ inputs.CROWDIN_DEVELOP_VERSION }}-exo
      PROJECT_BRANCH: develop-exo
    secrets: inherit
  # develop-meed workflow
  crowdin-download-develop-meed:
    if: always() && inputs.CROWDIN_ALLOW_DEVELOP_MEED_DOWNLOAD == 'true'
    needs: [crowdin-download-develop-exo]
    uses: exoplatform/swf-scripts/.github/workflows/download-crowdin-generic.yml@master
    with: 
      PROJECT_VERSION: ${{ inputs.CROWDIN_DEVELOP_VERSION }}-meed
      PROJECT_BRANCH: develop-meed
    secrets: inherit
  # stable/x.x.x-exo
  crowdin-download-stable-exo:
    if: always() && inputs.CROWDIN_ALLOW_MAINTENANCE_DOWNLOAD == 'true'
    needs: [crowdin-download-develop-meed]
    uses: exoplatform/swf-scripts/.github/workflows/download-crowdin-generic.yml@master
    with: 
      PROJECT_VERSION: ${{ inputs.CROWDIN_MAINTENANCE_EXO_VERSION }}-exo
      PROJECT_BRANCH: stable/${{ inputs.CROWDIN_MAINTENANCE_EXO_VERSION }}-exo
    secrets: inherit