name: Crowdin Upload branches

on:
  workflow_call:
    inputs:
      CROWDIN_MAINTENANCE_BRANCH_VERSION:
        description: Maintenance Crowdin branch
        default: "maintenance"
        required: false
        type: string
    secrets:
      CROWDIN_PROJECT_ID:
        required: true
      CROWDIN_PERSONAL_TOKEN:
        required: true
jobs:
  crowdin-upload-branches:
    uses: exoplatform/swf-scripts/.github/workflows/upload-crowdin-generic.yml@master
    with:
      CROWDIN_MAINTENANCE_BRANCH_VERSION: ${{inputs.CROWDIN_MAINTENANCE_BRANCH_VERSION}}
    secrets: inherit
