name: Crowdin Upload main

on:
  workflow_call:
    secrets:
      CROWDIN_PROJECT_ID:
        required: true
      CROWDIN_PERSONAL_TOKEN:
        required: true
jobs:
  crowdin-upload-main:
    uses: exoplatform/swf-scripts/.github/workflows/upload-crowdin-generic.yml@master
    secrets: inherit