name: eXo PR Task Webhook

on:
  pull_request:
    types: [opened, reopened, closed, review_requested]
  pull_request_review:
    types: [submitted]

jobs:
  puppet:
    name: Puppet
    uses: exoplatform/swf-scripts/.github/workflows/ghawebhooktasks.yml@gha